
#define LED_BLACK           0

#define LED_RED_VERYLOW    (3 <<  11)
#define LED_RED_LOW        (7 <<  11)
#define LED_RED_MEDIUM     (15 << 11)
#define LED_RED_HIGH       (31 << 11)

#define LED_GREEN_VERYLOW  (1 <<  5)
#define LED_GREEN_LOW      (15 << 5)
#define LED_GREEN_MEDIUM   (31 << 5)
#define LED_GREEN_HIGH     (63 << 5)

#define LED_BLUE_VERYLOW     3
#define LED_BLUE_LOW         7
#define LED_BLUE_MEDIUM     15
#define LED_BLUE_HIGH       31

#define LED_ORANGE_VERYLOW (LED_RED_VERYLOW + LED_GREEN_VERYLOW)
#define LED_ORANGE_LOW     (LED_RED_LOW     + LED_GREEN_LOW)
#define LED_ORANGE_MEDIUM  (LED_RED_MEDIUM  + LED_GREEN_MEDIUM)
#define LED_ORANGE_HIGH    (LED_RED_HIGH    + LED_GREEN_HIGH)

#define LED_PURPLE_VERYLOW (LED_RED_VERYLOW + LED_BLUE_VERYLOW)
#define LED_PURPLE_LOW     (LED_RED_LOW     + LED_BLUE_LOW)
#define LED_PURPLE_MEDIUM  (LED_RED_MEDIUM  + LED_BLUE_MEDIUM)
#define LED_PURPLE_HIGH    (LED_RED_HIGH    + LED_BLUE_HIGH)

#define LED_CYAN_VERYLOW   (LED_GREEN_VERYLOW + LED_BLUE_VERYLOW)
#define LED_CYAN_LOW       (LED_GREEN_LOW     + LED_BLUE_LOW)
#define LED_CYAN_MEDIUM    (LED_GREEN_MEDIUM  + LED_BLUE_MEDIUM)
#define LED_CYAN_HIGH      (LED_GREEN_HIGH    + LED_BLUE_HIGH)

#define LED_WHITE_VERYLOW  (LED_RED_VERYLOW + LED_GREEN_VERYLOW + LED_BLUE_VERYLOW)
#define LED_WHITE_LOW      (LED_RED_LOW     + LED_GREEN_LOW     + LED_BLUE_LOW)
#define LED_WHITE_MEDIUM   (LED_RED_MEDIUM  + LED_GREEN_MEDIUM  + LED_BLUE_MEDIUM)
#define LED_WHITE_HIGH     (LED_RED_HIGH    + LED_GREEN_HIGH    + LED_BLUE_HIGH)

#define BASLAMA_YAZI_SURE 100

#define OYUNCU1 '3'
#define OYUNCU2 '4'
#define SISTEM '5'

#define OYUNCU_BISIKLET_SECIMI 'B'
#define JETON_AT 'A'

#define OYUNCU_MOD_SECIMI 'M'
#define OYUNCU_MOD_SECIM_SONU 'm'
#define OYUNMOD_SECME_SURESI 10000

#define OYUN_OYNANAN_SURE 'O'
#define OYUN_BITTI 'E'

#define OYUNCU_HIZ_VERI 'V'
#define OYUNCU2_HIZ_VERI 'v'

#define OYUNCU_TEKERLEK_DONME_SAYISI 'D'
#define OYUNCU2_TEKERLEK_DONME_SAYISI 'D'

#define OYUNCU_TUR_SAYISI 'T'
#define BOS_ANIM_EKRANI 'K'

#define OYUNCU_YARIS_SIRA1 '1'
#define OYUNCU_YARIS_SIRA2 '2'
#define OYUNCU_YARIS_SIRA0 '0'


#define BAY_MOD 0
#define BAYAN_MOD 1
#define COCUK_MOD 2
